// Created using Gameboy Tile Designer (GBTD) v2.2

#ifndef __GRIDWALKER_SPRITES_H__
#define __GRIDWALKER_SPRITES_H__

#include <stdint.h>

// ------------------------------------------------------------------------------------

#define SPRITE_EMPTY_INDEX 0

// font
#define SPRITE_BASIC_FONT_A_INDEX 1
#define SPRITE_BASIC_FONT_B_INDEX 2
#define SPRITE_BASIC_FONT_C_INDEX 3
#define SPRITE_BASIC_FONT_D_INDEX 4
#define SPRITE_BASIC_FONT_E_INDEX 5
#define SPRITE_BASIC_FONT_F_INDEX 6
#define SPRITE_BASIC_FONT_G_INDEX 7
#define SPRITE_BASIC_FONT_H_INDEX 8
#define SPRITE_BASIC_FONT_I_INDEX 9
#define SPRITE_BASIC_FONT_J_INDEX 10
#define SPRITE_BASIC_FONT_K_INDEX 11
#define SPRITE_BASIC_FONT_L_INDEX 12
#define SPRITE_BASIC_FONT_M_INDEX 13
#define SPRITE_BASIC_FONT_N_INDEX 14
#define SPRITE_BASIC_FONT_O_INDEX 15
#define SPRITE_BASIC_FONT_P_INDEX 16
#define SPRITE_BASIC_FONT_Q_INDEX 17
#define SPRITE_BASIC_FONT_R_INDEX 18
#define SPRITE_BASIC_FONT_S_INDEX 19
#define SPRITE_BASIC_FONT_T_INDEX 20
#define SPRITE_BASIC_FONT_U_INDEX 21
#define SPRITE_BASIC_FONT_V_INDEX 22
#define SPRITE_BASIC_FONT_W_INDEX 23
#define SPRITE_BASIC_FONT_X_INDEX 24
#define SPRITE_BASIC_FONT_Y_INDEX 25
#define SPRITE_BASIC_FONT_Z_INDEX 26
#define SPRITE_BASIC_FONT_0_INDEX 27
#define SPRITE_BASIC_FONT_1_INDEX 28
#define SPRITE_BASIC_FONT_2_INDEX 29
#define SPRITE_BASIC_FONT_3_INDEX 30
#define SPRITE_BASIC_FONT_4_INDEX 31
#define SPRITE_BASIC_FONT_5_INDEX 32
#define SPRITE_BASIC_FONT_6_INDEX 33
#define SPRITE_BASIC_FONT_7_INDEX 34
#define SPRITE_BASIC_FONT_8_INDEX 35
#define SPRITE_BASIC_FONT_9_INDEX 36
#define SPRITE_BASIC_FONT_PERIOD_INDEX 37
#define SPRITE_BASIC_FONT_EXCLAMATION_INDEX 38
#define SPRITE_BASIC_FONT_QUESTION_INDEX 39

// cursors
#define SPRITE_CURSOR_SINGLE_PIECE_INDEX 40
#define SPRITE_CURSOR_TWO_PIECE_START_INDEX 41
#define SPRITE_CURSOR_TWO_PIECE_END_INDEX 42
#define SPRITE_CURSOR_FOUR_PIECE_START_INDEX 43
#define SPRITE_CURSOR_FOUR_PIECE_END_INDEX 46

#define LAST_SPRITE_INDEX 46

// ------------------------------------------------------------------------------------

extern const uint8_t k_gridwalker_sprites[];

#endif // __GRIDWALKER_SPRITES_H__